### ISSUE TITLE
encode as array(*) and primitive  

### ISSUE THREAD

**Issue by ashisherc** [hildjj/node-cbor#112]
I wanted to encode some data as array(*) when the array length is more then certain limit, this is how a data Im parsing has encoded, when I decode the data and encode back, I get a different cbor hash,

@hildjj can you please help what can be done here, is there a way I can just traverse the cbor without decoding and create a hash out of the certain part of a cbor?

**Comment by hildjj** [comment]
For encoding, see #107.  Another approach would be to use the eventing system that Decoder has in order to see the raw bytes.  See commented.js for an example.

**Comment by ashisherc** [comment]
continued here, https://github.com/hildjj/node-cbor/issues/107
