### ISSUE TITLE
traverse cbor without decoding to hash certain part of a cbor

### ISSUE THREAD

**Issue by ashisherc** [hildjj/node-cbor#113]
I want to hash certain parts of a cbor by traversing through the cbor and hash content. If I decode and encode the data types changes from previous ones due to the fact how js represents some data types.

**Comment by hildjj** [comment]
Look at `lib/commented.js` for examples of how to see the bytes as they go by during decoding.

**Comment by ashisherc** [comment]
continued here, https://github.com/hildjj/node-cbor/issues/114#issue-672500144
