### ISSUE TITLE
How to decodeFirst while ignoring extra data?

### ISSUE THREAD

**Issue by mcclure** [hildjj/node-cbor#118]
The [doc](http://hildjj.github.io/node-cbor/Decoder.html#.decodeFirst) for `decodeFirst` says, my emphasis:

> Decode the first CBOR item in the input. **This will error if there are more bytes left over at the end**

Several things are confusing me.

* I specifically want to interpret data which consists of CBOR items interleaved with other binary items. I was hoping node-cbor could read the first whole CBOR item and then return control to my code, either consuming the CBOR item from something like a stream or returning the offset of the first byte after the first CBOR item. My code would then, after reading the CBOR item, decide whether to read another CBOR item or to do something else with the remaining binary. Is this possible with node-cbor?
* It doesn't make sense to me why a "decodeFirst" function would have a requirement that it consume its entire input. That sounds more like a "decodeOne" sort of operation.
* The "This will error if there are more bytes left over at the end" language is present in the docs for "decodeFirst", but not for "decodeFirstSync". Is one of the two function docs in error?
* Despite this, eyeballing the source code, I'm not sure I understand it but it looks (?) like there is a specific check for additional data at the end for decodeFirstSync, but I don't see such a check at the end of decodeFirst.

Given all this, my questions:

- Is the documentation for decodeFirst and decodeFirstSync both accurate?
- How do I consume the first CBOR item in a stream/arraybuffer while leaving the remaining bytes for future operations?

**Comment by mcclure** [comment]
Testing, I fed an ArrayBufferView containing [one CBOR item and then extra bytes] to decodeFirst. I still don't know how to decode an item and then get the index following the decoded item, but it does appear the claim in the decodeFirst docs "This will error if there are more bytes left over at the end" is incorrect. I did not get an error.

**Comment by hildjj** [comment]
I also fixed the docs to make it clear that both `decodeFirst` and `decodeFirstSync` will throw errors if there is extra data and you haven't specified `{extendedResults: true}`.

I'll do a release tomorrow if you agree this fixes your issue.

**Comment by hildjj** [comment]
Example:
```js
cbor.decodeFirstSync('6161f6', {extendedResults: true})
// { value: 'a', bytes: <Buffer 61 61>, length: 2, unused: <Buffer f6> }
```

**Comment by hildjj** [comment]
this is in 6.0.1

**Comment by mcclure** [comment]
This is great, thank you, I think this is exactly what I needed, I might not have time to test it for a bit tho
