### ISSUE TITLE
Module not found: Error: Can't resolve 'stream'

### ISSUE THREAD

**Issue by badboy-huaqiao** [hildjj/node-cbor#132]
Angular11

`Error: ./node_modules/cbor/lib/commented.js
Module not found: Error: Can't resolve 'stream' in '/Users/..../node_modules/cbor/lib'
`

**Comment by hildjj** [comment]
require `stream-browserify` in your project?

**Comment by hildjj** [comment]
See https://github.com/Richienb/node-polyfill-webpack-plugin/blob/master/index.js for other things you might need.

**Comment by badboy-huaqiao** [comment]
@hildjj my project is angular11 and using ng-cli init my project, so your mean that I need use `npm install stream-browserify` ? is that right?

**Comment by hildjj** [comment]
See https://github.com/hildjj/node-cbor/pull/130#issuecomment-770284674 for the conversation we're having about how to make this work today, and what we might do to make it easier.

**Comment by badboy-huaqiao** [comment]
@hildjj ok, great thanks, I wish that works after your PR is merged.

**Comment by hildjj** [comment]
`cbor-web` is now published at version 7.0.0, it's what you want.
