### ISSUE TITLE
`node-inspect-extracted` missing in dependencies

### ISSUE THREAD

**Issue by letmaik** [hildjj/node-cbor#141]
The `cbor` package imports `node-inspect-extracted` but doesn't declare it as dependency.

**Comment by hildjj** [comment]
I don't think making node-inspect-extracted an optional peer dependency really captures the gist of what's wanted here, which is that node users don't ever see the dependency.  I'm thinking about adding a plugin API anyway, because of #140.

I'm open to suggestions.

**Comment by hildjj** [comment]
Subpath imports require node 12.  I'm not quite ready to pull that trigger yet; I'm waiting to see how https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c plays out

**Comment by letmaik** [comment]
node 12 is the current LTS and node 10 is EOL and won't be security patched anymore. Any reason you want to keep supporting node 10?

**Comment by lukem512** [comment]
+1 for this. I've had to use `cbor-web` for the moment but it doesn't feel like a nice solution.

**Comment by letmaik** [comment]
I've switched to https://github.com/aaronhuggins/cbor-redux for now as it's very lightweight (no dependencies) and can run in any JS environment. It would be nice if node-cbor eventually is restructured to support such use cases. I realize there are some challenges with making this compatible with the streaming interface but I have a feeling most people will use the simple interface anyway?

**Comment by hildjj** [comment]
I've got a much simpler interface currently in https://github.com/hildjj/cbor-wasm but it's not done yet.

**Comment by letmaik** [comment]
Interesting, in my case I would also need an encoder and can't run wasm currently.

**Comment by hildjj** [comment]
Update: I'll do the update to require node 12 soon after Ava releases their [4.0](https://github.com/avajs/ava/milestone/5) version.

**Comment by hildjj** [comment]
Please retest with v8.0.0 and reopen if this isn't fixed.
