### ISSUE TITLE
Loss of Precision when Parsing Date Strings

### ISSUE THREAD

**Issue by JesusMcCloud** [hildjj/node-cbor#146]
Date Strings can represent timestamps with nanosecond-precision, while JS's date class cannot.
This GH-145 addresses this issue and returns date strings verbatim

**Comment by hildjj** [comment]
As a work-around, you can use code like this:

```js
cbor.decodeFirstSync(input, {
  tags: {
    0: x => x
  }
})
```

which may be more concise than adding a preference.

**Comment by JesusMcCloud** [comment]
Thanks for the support! This works well for our case. Maybe even a note in the README would suffice, given how easy it si to deal with it?

**Comment by hildjj** [comment]
See the text I added at https://github.com/hildjj/node-cbor/pull/147/files#diff-358273ba3280ca05870b503d54d3908dca434851fab72f89bceac10784ccb0a4R236 and either comment on the PR or here, please.

**Comment by JesusMcCloud** [comment]
Perfect, thanks for all the help!
In my opinion GH-147 fixes this, as the behaviour is clearly documented.
