### ISSUE TITLE
Error: Unexpected data: 0x44

### ISSUE THREAD

**Issue by iamgabrielsoft** [hildjj/node-cbor#157]
Why getting this error while 
`

decodeFirst`

Please somebody respond to this....

**Comment by hildjj** [comment]
Can you give me more information, please?  I think your report got its formatting confused a little.

**Comment by iamgabrielsoft** [comment]
yeah sure... 

I was using the cbor package to decode a message but ran into this error ----> Error: Unexpected data: 0x44

**Comment by iamgabrielsoft** [comment]
return cbor.decodeFirst(payload)
        .then((obj) => {
          let type = options.defaultType ? options.defaultType : this.Signtag;
          if (obj instanceof Tagged) {
            if (obj.tag !== this.Signtag && obj.tag !== this.Sign1Tag) {
              throw new Error('Unexpected cbor tag, \'' + obj.tag + '\'');
            }
            type = obj.tag;
            obj = obj.value;
          }

   });``

**Comment by hildjj** [comment]
Your payload includes multiple cbor data items.

```js
const result = await cbor.decodeFirst('014401020304')
```

where the first byte (`01`) is a complete CBOR data item, and decodeFirst by default throws an error in that situation.  Try this:

```js
const extendedResult = await cbor.decodeFirst('0144', {extendedResults: true})
// { value: 1, bytes: <Buffer 01>, length: 1, unused: <Buffer 44> }
const result = extendedResult.value
```

Alternately, it is more efficient to treat the decoder as  a stream:

```js
const d = new cbor.Decoder()
d.on('data', value => console.log(value))
d.write(payload)
```

**Comment by iamgabrielsoft** [comment]
Of course you cbor is not a class... 

initiating it this way ---  TypeError: Class constructor Decoder cannot be invoked without 'new'

**Comment by hildjj** [comment]
`cbor.Decoder` is a class.  `cbor.decodeFirst` is a function, which is also available as `cbor.Decoder.decodeFirst`.

**Comment by iamgabrielsoft** [comment]
Error: Unexpected data: 0x44. Sorry but till getting the error

**Comment by hildjj** [comment]
Can you please post the code that you're currently running?

**Comment by iamgabrielsoft** [comment]
return cbor.decodeFirst(payload)
        .then((obj) => {
          let type = options.defaultType ? options.defaultType : this.Signtag;
          if (obj instanceof Tagged) {
            if (obj.tag !== this.Signtag && obj.tag !== this.Sign1Tag) {
              throw new Error('Unexpected cbor tag, \'' + obj.tag + '\'');
            }
            type = obj.tag;
            obj = obj.value;
          }

          if (!Array.isArray(obj)) {
            throw new Error('Expecting Array');
          }

          if (obj.length !== 4) {
            throw new Error('Expecting Array of lenght 4');
          }

          let [p, u, plaintext, signers] = obj;

          if (type === SignTag && !Array.isArray(signers)) {
            throw new Error('Expecting signature Array');
          }

          p = (!p.length) ? this.EMPTY_BUFFER : cbor.decodeFirstSync(p);
          u = (!u.size) ? this.EMPTY_BUFFER : u;

          let signer = (type === SignTag ? this.getSigner(signers, verifier) : signers);

          if (!signer) {
            throw new Error('Failed to find signer with kid' + verifier.key.kid);
          }

          if (type === SignTag) {
            const externalAAD = verifier.externalAAD || this.EMPTY_BUFFER;
            let [signerP, , sig] = signer;
            signerP = (!signerP.length) ? this.EMPTY_BUFFER : signerP;
            p = (!p.size) ? this.EMPTY_BUFFER : cbor.encode(p);
            const signerPMap = cbor.decode(signerP);
            const alg = signerPMap.get(Common.HeaderParameters.alg);
            const SigStructure = [
              'Signature',
              p,
              signerP,
              externalAAD,
              plaintext
            ];
            return this.doVerify(SigStructure, verifier, alg, sig)
              .then(() => {
                return plaintext;
              });
          } else {
            const externalAAD = verifier.externalAAD || this.EMPTY_BUFFER;

            const alg = this.getCommonParameter(p, u, Common.HeaderParameters.alg);
            p = (!p.size) ? this.EMPTY_BUFFER : cbor.encode(p);
            const SigStructure = [
              'Signature1',
              p,
              externalAAD,
              plaintext
            ];


            return this.doVerify(SigStructure, verifier, alg, signer)
              .then(() => {
                return plaintext;
              });
          }
        });

**Comment by iamgabrielsoft** [comment]
The paramters am passing are in Buffer

**Comment by hildjj** [comment]
change the first two lines to:

```js
return cbor.decodeFirst(payload, {extendedResults: true})
    .then(({value: obj}) => {
```

**Comment by iamgabrielsoft** [comment]
return cbor.decodeFirst(payload, {extendedResults: true})
        .then(({value: obj}) => {
          console.log("value", obj)
})


Till the same

**Comment by hildjj** [comment]
what is the output of:

```js
return cbor.decodeFirst(payload, {extendedResults: true})
.catch(e => console.log(payload.toString('hex'))
```

**Comment by iamgabrielsoft** [comment]
Error: Unexpected data: 0x44
    at Decoder._parse (C:\Users\Softbook\Documents\Main Programs\Open Source\cose-js\node_modules\cbor\lib\decoder.js:357:15)
    at _parse.next (<anonymous>)
    at Decoder.BinaryParseStream._transform (C:\Users\Softbook\Documents\Main Programs\Open Source\cose-js\node_modules\cbor\vendor\binary-parse-stream\index.js:35:31)
    at Decoder.Transform._read (internal/streams/transform.js:205:10)
    at Decoder.Transform._write (internal/streams/transform.js:193:12)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Decoder.Writable.write (internal/streams/writable.js:303:10)
    at Decoder.Writable.end (internal/streams/writable.js:567:10)
    at Object.decodeFirst (C:\Users\Softbook\Documents\Main Programs\Open Source\cose-js\node_modules\cbor\lib\decoder.js:282:7)
    at Sign.verify (C:\Users\Softbook\Documents\Main Programs\Open Source\cose-js\lib\sign.js:177:32)``

**Comment by hildjj** [comment]
Do you have another place where you're calling `decodeFirst` than the one you changed?

**Comment by iamgabrielsoft** [comment]
yeah i do but passing a payload parameter

**Comment by iamgabrielsoft** [comment]
in another file

**Comment by hildjj** [comment]
Is your full project available on GitHub or somewhere else where I can see it?

**Comment by hildjj** [comment]
Or mail me a zip file to the email address in the package.json file for cbor.

**Comment by iamgabrielsoft** [comment]
https://github.com/iamgabrielsoft/cose-js

**Comment by iamgabrielsoft** [comment]
sorry this --> https://github.com/iamgabrielsoft/cose-js/blob/master/lib/sign.js#L186

**Comment by hildjj** [comment]
First off, you're using an *ancient* version of the cbor package.  Please update to the latest.

**Comment by iamgabrielsoft** [comment]
hahaha😜

**Comment by iamgabrielsoft** [comment]
to what version??

**Comment by iamgabrielsoft** [comment]
i installed version + cbor@3.0.3

Till the same error

**Comment by hildjj** [comment]
Try installing cbor@8.0.0

**Comment by hildjj** [comment]
I use https://github.com/raineorshine/npm-check-updates to ensure all of my dependencies are up-to-date.

**Comment by iamgabrielsoft** [comment]
yeah siure... 

now getting err UnexpectedDataError: Unexpected data: 0x44

**Comment by hildjj** [comment]
How are you getting this error to occur?  I updated my local copy of your repo to cbor@8, pulled in the git submodules, and all of the tests pass.

**Comment by iamgabrielsoft** [comment]
wooow....

**Comment by iamgabrielsoft** [comment]
Probably am runing the example file sepately...

**Comment by hildjj** [comment]
Also, it looks like you changed one instance of `decodeFirst` (in encrypt.js), but there are several more.  In particular, ensure that you've changed the one on line 188 of sign.js.

**Comment by hildjj** [comment]
This is likely an issue in how you are calling @erdtman's code.  Perhaps you could get his help.
