### ISSUE TITLE
react-native-cli

### ISSUE THREAD

**Issue by hildjj** [hildjj/node-cbor#162]
Hi! First of all great that you have implemented this package for RN!
However I can't get this to work with react-native-cli (not Expo)

When i try to require _cbor-rn-prereqs_ i get a following error:

``$ Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.``

 ``$ ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.``

I tried cleaning the project, uninstalling and installing dependencies again - restarting terminals and caches, deleting the bundle from the devices/simulators - but this error persists.

If you are interested [this is a fresh RN project I tried to apply this configuration with.](https://github.com/rottabonus/rn-testing-cbor) 

Also happy to give more details! I would love to help debugging this, but I'm afraid I am so fresh, I don't have any idea from where to start.. Cheers!

_Originally posted by @rottabonus in https://github.com/hildjj/node-cbor/issues/158#issuecomment-961733887_

**Comment by hildjj** [comment]
I really don't want to install all of Android Studio to reproduce this.  Can someone else help, please?

**Comment by hildjj** [comment]
OK, I finally got the iOS target running, and it has the same issue.  I think I've got it nailed down, but will require a release of `@cto.af/textdecoder` as well.

**Comment by hildjj** [comment]
Fixed for ios in 8.1.0, please test with Android, and re-open this issue if needed.

**Comment by rottabonus** [comment]
Wow, you are a star! I tested with Android emulator and device. Works fine!

**Comment by hildjj** [comment]
For those who come along later, read the instructions [here](https://github.com/hildjj/node-cbor/tree/main/packages/cbor-rn-prereqs) for how to work around ReactNative's non-modern implementation of JavaScript.
