### ISSUE TITLE
Type array tags CBOR

### ISSUE THREAD

**Issue by Ottunger** [hildjj/node-cbor#174]
When we know that resulting Buffer (or Uint8Array in case of cbor-web) is to be used as part of a larger CBOR payload, it should be encoded using tag 24.

Is there any way to pass to `encodeOne` an overwrite for the tag to apply on typed array, say `bufferTagType` much like there already exists `dateType`? This would be used on the top-level `encode` operation.

**Comment by Ottunger** [comment]
We could solve our issue using `genTypes`, specifically:

```
const EmbeddedCBORGenTypes = {
    Uint8Array: (gen: Encoder, obj: Uint8Array) => {
        if(!gen._pushTag(0b00011000)) {
            return false;
        }
        return CBOR.Encoder._pushBuffer(gen, Buffer.from(obj))
    }
};
```

It's not perfect but it does the job.
Is it worth searching for an alternative?

**Comment by hildjj** [comment]
You could wrap your Buffer in a Tag, like so:

```js
const buf = cbor.encode(...)
const t = new cbor.Tagged(24, buf)
return cbor.encode(t)
```

**Comment by hildjj** [comment]
I think the solution above is fine.  Re-open if you'd like another approach.
