### ISSUE TITLE
cbor tagged object not same after decoding and again encoding

### ISSUE THREAD

**Issue by Veeramani41** [hildjj/node-cbor#181]
cbor tagged object not same after decoding and again encoding.

steps: creating cbor with 0 tag like  cbor = 0("2023-07-21T07:10:09Z")
when decoding the above cbor it is coming with datetime value with localtime zone.

then again if try to encode the cbor it is tagged as 1(1689923409)

it is creating problem while persisting the data and again try to reuse the same data.

**Comment by hildjj** [comment]
pass `dateType = 'string'` into the encoder?

**Comment by Veeramani41** [comment]
is there anyway to stop tagged object decoding and I need to get actual tagged object instead of decoded value. I need to persist all the tags in the data.

**Comment by hildjj** [comment]
Yep.  Pass `tags = {}` in the decoder options.  If you want to decode some tags and not others, you can make a copy of `cbor.Tagged.TAGS`, modify it however you like, and pass that in for the `tags` option.

**Comment by Veeramani41** [comment]
I tried tags: {} in the decoder options. it is not working, still decodes the tagged object.

**Comment by hildjj** [comment]
It's going to be `{tags: {1: null}}`, but there's a bug I need to fix before that works like the docs say it does.

**Comment by hildjj** [comment]
From the test I just added in #31 

```js
  const buf = Buffer.from('c100', 'hex');
  t.deepEqual(cbor.decode(buf), new Date(0));
  t.deepEqual(cbor.decode(buf, {tags: {1: null}}), new cbor.Tagged(1, 0));
```

9.0.1 release forthcoming.

**Comment by hildjj** [comment]
I opened this back up to make sure that 9.0.1 fixes your issue.  Will close when you confirm.

**Comment by Veeramani41** [comment]
now the issue has been fixed
