### ISSUE TITLE
empty maps parsed as objects, not maps

### ISSUE THREAD

**Issue by janmazak** [hildjj/node-cbor#186]
It seems that CBOR `a0` is parsed as an empty object, not a Map. Subsequent validations like `data instanceof Map` thus do not work. It would be more appropriate to parse it as `new Map()`.

**Comment by Wind4Greg** [comment]
Also seeing this problem arise.

**Comment by hildjj** [comment]
I can add an option to always produce maps.

**Comment by janmazak** [comment]
That would be great. Thanks.

**Comment by hildjj** [comment]
Please review #189
