### ISSUE TITLE
cbor & cbor-web encoding is diffrent

### ISSUE THREAD

**Issue by rickhaer** [hildjj/node-cbor#214]
Hi, im currently implementing encoding for my cbor data and was hoping I could do this using the cbor web package but for some reason it is not giving me the correct results.

I tried it using the cbor package which is running with node with a small backend and this encodes my data correctly.*

When encoding my data cbor-web gives me;

`const taggedUUID = new cbor.Tagged(37, uuidArray);` -> `37(64(h'5DC48304532E4E6BAA6DDF5CF049BB7C'))`
`[[0, 65, 1, {0: 37(64(h'5DC48304532E4E6BAA6DDF5CF049BB7C')), 1: 1}]]`

while cbor gives me (which is what i need):

`[[0, 65, 1, {0: 37(h'5DC48304532E4E6BAA6DDF5CF049BB7C'), 1: 1}]]`

Differnce is:
cbor-web wraps the binary data h'5DC48304532E4E6BAA6DDF5CF049BB7C' in an extra 64 tag. Is there any configuration to avoid this and getting the some result with cbor-web than with cbor package?

**Comment by hildjj** [comment]
I was unclear.  What you *want* is really reasonable.  That there is not config option is unreasonable. :)

**Comment by rickhaer** [comment]
@hildjj Thanks for your answer! :) Didn't know about cbor2 yet, tried it, was some stuff to rebuild and change but works like a charm now with cbor2, thanks!

Maybe you could put a notice here https://www.npmjs.com/package/cbor-web that you will recommend cbor2 from now on.

**Comment by hildjj** [comment]
Great idea.

**Comment by hildjj** [comment]
Fixed in 10.0.3
