### ISSUE TITLE
sync decode

### ISSUE THREAD

**Issue by dominictarr** [hildjj/node-cbor#24]
It's great that you support streaming decode, but the decoder itself shouldn't need to be async.
If I do happen to have an entire object, you ought to be able to parse it synchronously,
without using a callback or a promise.

This module would be easier to use if had sync {encode, decode}, actually that means it could be a leveldb codec! https://github.com/Level/levelup#custom_encodings That would mean it has the same api as a bunch of other serialization modules, which means it is easy to switch to cbor!

**Comment by hildjj** [comment]
@dominictarr: please try `cbor.leveldb`, and let me know if it works or not.
