### ISSUE TITLE
Documentation link is broken

### ISSUE THREAD

**Issue by agronholm** [hildjj/node-cbor#32]
The documentation link (http://hildjj.github.io/node-cbor/doc/) gives a 404.

**Comment by hildjj** [comment]
Willfix.

**Comment by hildjj** [comment]
Please test again, and reopen if you find another bad link.

**Comment by agronholm** [comment]
It's still broken. http://hildjj.github.io/node-cbor/api/ still refers to http://hildjj.github.io/node-cbor/doc/ which gives a 404.

**Comment by hildjj** [comment]
Well to be fair, on that page, you're already on that page.   :)

But fixed, by re-creating the API docs from the modified README.  Try that?

**Comment by agronholm** [comment]
I cannot find the full API documentation anywhere, so I was hoping the link would take me there. Now it just loops back to the same page. That page contains only examples, but no API documentation. For example, nowhere does it say which CBOR extension types are supported. And if there are any ways to extend it, this is not documented as far as I can see.

**Comment by agronholm** [comment]
Also I have no idea what you mean by re-creating the API docs from the modified README.

**Comment by hildjj** [comment]
Click on "Classes" at the top.  Do you want to encode or decode?  For the decoder, pass in an options object with `tags` set.  For the encoder, call `addSemanticType` before encoding.

The new documentation format isn't that discoverable, and that there needs to be an example for tag extension in each direction, so I re-opened the issue.

**Comment by agronholm** [comment]
Ah, I completely missed that. But is there a list of supported semantic tags anywhere? A quick tryout revealed that at least Date and Regexp are supported. What about shared references?

**Comment by hildjj** [comment]
Start with this list, and I'll make it more formal in the docs.

https://github.com/hildjj/node-cbor/blob/f4e6a1b47963212ad66322503880ec928f7ceddc/lib/encoder.js#L48

**Comment by agronholm** [comment]
Thanks. For reference, here's mine: https://pypi.org/project/cbor2/

**Comment by hildjj** [comment]
OK, let me know if that isn't clear enough, and I'll open this back up again.  If you'd like me to support types I don't yet, send PRs.  If you'd like it to be easier to add encoders and decoders at the same time, I'm considering the cleanest way of doing that in a backward-compatible fashion.

**Comment by agronholm** [comment]
http://hildjj.github.io/node-cbor/api/ now gives me a 404.

**Comment by hildjj** [comment]
There shouldn't be any links to there anymore.  Try: https://hildjj.github.io/node-cbor/

**Comment by agronholm** [comment]
Ah, this looks much better, thanks! You should probably remove that confusing link ("See the full API documentation.") now. Good work!

**Comment by hildjj** [comment]
That link is needed here (which is generated from the same file): https://github.com/hildjj/node-cbor#documentation

Am open to suggestions.

**Comment by agronholm** [comment]
Okay, never mind then :)

**Comment by hildjj** [comment]
Oh, and update to v2.0.1 for the documentation to match the code.
