### ISSUE TITLE
Nested Map Issue

### ISSUE THREAD

**Issue by daveismith** [hildjj/node-cbor#42]
I'm trying to decode a structure with nested maps and having a number of issues. Here's my test:

```
var cbor = require('cbor');

cbor.decodeFirst('a46161a200a161720111a16172016162191388626d6e00626d7819fffe', function(err, val) {
   console.log('val(a): ' + JSON.stringify(val));
});

cbor.diagnose('a46161a200a161720111a16172016162191388626d6e00626d7819fffe', function(err, val) {
   console.log('diag(a): ' + val);
});

cbor.decodeFirst('a26161a200a161720111a16172016162191388', function(err, val) {
   console.log('val(b): ' + JSON.stringify(val));
});

cbor.diagnose('a26161a200a161720111a16172016162191388', function(err, val) {
   console.log('diag(b): ' + val);
});
```

the output I get is

```
val(a): {"a":{},"b":5000,"mn":0,"mx":65534}
val(b): {"a":{},"b":5000}
diag(a): {"a": {0: {"r": 1}, 17: {"r": 1}}, "b": 5000, "mn": 0, "mx": 65534}

diag(b): {"a": {0: {"r": 1}, 17: {"r": 1}}, "b": 5000}

```

the diag outputs are what I expect. The comment function also seems to display the maps. If I add code that prints every time a map is encountered I can see that the event the decode command is actually walking through all levels, they just don't seem to be added to the actual object that is output.

**Comment by daveismith** [comment]
Nevermind, this was an issue with the fact I'm using numeric keys. They're getting put into maps and for some reason JSON.stringify doesn't want to handle that.

**Comment by hildjj** [comment]
I'm glad you found an answer for this; I was struggling to figure out what was going on. :)
