### ISSUE TITLE
ES2015 ArrayBuffers instead of node.js Buffers

### ISSUE THREAD

**Issue by apowers313** [hildjj/node-cbor#52]
It would be nice if there were a way for the parser to generate [ES2015 ArrayBuffers](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer) rather than [node.js Buffers](https://nodejs.org/api/buffer.html), for compatibility with APIs that will be consuming ArrayBuffers. Otherwise, it becomes necessary to recursively find and convert Buffers to ArrayBuffers.

**Comment by hildjj** [comment]
Are you sure you want an ArrayBuffer, not a Uint8Array?

**Comment by hildjj** [comment]
if anyone has a half-decent argument for ArrayBuffer, I'll change the patch.   Waiting a few days before I land it.
