### ISSUE TITLE
nested object shown as [Object] with decodeAll

### ISSUE THREAD

**Issue by jacobrosenthal** [hildjj/node-cbor#56]
using decodeAllSync on this hex string

Buffer.from([0xbf, 0x6a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x19, 0x26, 0xfc, 0x64, 0x6c, 0x6f, 0x67, 0x73, 0x9f, 0xbf, 0x64, 0x6e, 0x61, 0x6d, 0x65, 0x6a, 0x72, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x64, 0x74, 0x79, 0x70, 0x65, 0x02, 0x67, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x9f, 0xbf, 0x63, 0x6d, 0x73, 0x67, 0x78, 0x21, 0x72, 0x73, 0x6e, 0x3a, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x45, 0x44, 0x2c, 0x20, 0x63, 0x6e, 0x74, 0x3a, 0x30, 0x2c, 0x20, 0x69, 0x6d, 0x67, 0x3a, 0x30, 0x2e, 0x30, 0x2e, 0x30, 0x2e, 0x30, 0x62, 0x74, 0x73, 0x1a, 0x1a, 0xce, 0xa3, 0xc0, 0x65, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x04, 0x65, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x19, 0x26, 0xfb, 0x66, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x06, 0xff, 0xff, 0xff, 0xff, 0x62, 0x72, 0x63, 0x00, 0xff)]

is decoding as [ { next_index: 9980, logs: [ [Object] ], rc: 0 } ]

but should decode as 

{"next_index": 9980, "logs": [{"name": "reboot_log", "type": 2, "entries": [{"msg": "rsn:REQUESTED, cnt:0, img:0.0.0.0", "ts": 449749952, "level": 4, "index": 9979, "module": 6}]}], "rc": 0}

an online decode I got that from if it helps
http://cbor.me/?bytes=bf.6a.6e.65.78.74.5f.69.6e.64.65.78.19.26.fc.64.6c.6f.67.73.9f.bf.64.6e.61.6d.65.6a.72.65.62.6f.6f.74.5f.6c.6f.67.64.74.79.70.65.02.67.65.6e.74.72.69.65.73.9f.bf.63.6d.73.67.78.21.72.73.6e.3a.52.45.51.55.45.53.54.45.44.2c.20.63.6e.74.3a.30.2c.20.69.6d.67.3a.30.2e.30.2e.30.2e.30.62.74.73.1a.1a.ce.a3.c0.65.6c.65.76.65.6c.04.65.69.6e.64.65.78.19.26.fb.66.6d.6f.64.75.6c.65.06.ff.ff.ff.ff.62.72.63.00.ff

**Comment by hildjj** [comment]
WFM.  Remember, console.log doesn't expand to full depth by default:

```js
let b = Buffer.from([0xbf, 0x6a, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x19, 0x26, 0xfc, 0x64, 0x6c, 0x6f, 0x67, 0x73, 0x9f, 0xbf, 0x64, 0x6e, 0x61, 0x6d, 0x65, 0x6a, 0x72, 0x65, 0x62, 0x6f, 0x6f, 0x74, 0x5f, 0x6c, 0x6f, 0x67, 0x64, 0x74, 0x79, 0x70, 0x65, 0x02, 0x67, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x9f, 0xbf, 0x63, 0x6d, 0x73, 0x67, 0x78, 0x21, 0x72, 0x73, 0x6e, 0x3a, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x45, 0x44, 0x2c, 0x20, 0x63, 0x6e, 0x74, 0x3a, 0x30, 0x2c, 0x20, 0x69, 0x6d, 0x67, 0x3a, 0x30, 0x2e, 0x30, 0x2e, 0x30, 0x2e, 0x30, 0x62, 0x74, 0x73, 0x1a, 0x1a, 0xce, 0xa3, 0xc0, 0x65, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x04, 0x65, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x19, 0x26, 0xfb, 0x66, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x06, 0xff, 0xff, 0xff, 0xff, 0x62, 0x72, 0x63, 0x00, 0xff])
let o = cbor.decode(b)
console.log(util.inspect(o, {depth: null}))
```
Output:
```
{ next_index: 9980,
  logs:
   [ { name: 'reboot_log',
       type: 2,
       entries:
        [ { msg: 'rsn:REQUESTED, cnt:0, img:0.0.0.0',
            ts: 449749952,
            level: 4,
            index: 9979,
            module: 6 } ] } ],
  rc: 0 }
```

**Comment by jacobrosenthal** [comment]
Oh man Didn't even consider that. Thanks and sorry for the noise.

**Comment by jacobrosenthal** [comment]
Interestingly, even util.inspect was printing object occasionally. I got it finally with JSON.stringify
