### ISSUE TITLE
Keep input bytes from Decoder

### ISSUE THREAD

**Issue by hildjj** [hildjj/node-cbor#6]
When reading from a Decoder, add an option not to discard the bytes from the input.  The callback would then get a JavaScript object as well as the bytes that were decoded.  This would be used in situations where you want to process the JS, then pass the bytes along unmodified.

**Comment by ashisherc** [comment]
I think this https://github.com/hildjj/node-cbor/issues/113 is related to this issue

**Comment by hildjj** [comment]
I think `{extendedResults: true}` in the options does close enough to this.
