### ISSUE TITLE
Finish implementation of value-sharing

### ISSUE THREAD

**Issue by BurtHarris** [hildjj/node-cbor#69]
It looks like the work for the CBOR value-sharing extension <http://cbor.schmorp.de/value-sharing> is partially done, but not complete.   The tag values 28 and 29 permit a better response to detecting a duplicate object than is currently implemented [`throw new Error('Loop detected while CBOR encoding')`]

Issue #35 seems like it was intended to track this but perhaps the full idea behind the value-sharing proposal wasn't well expressed.   Looking at the code in sandhawke/borc-refs I'm not sure his encoder actually add the tags needed to flesh this out.

Thinking about the implementation of encoding with shared objects, an approach based on WeakMap seems more clean to me than coloring the actual objects using Symbols, though I agree the symbols are unlikely to hurt things.   Was this approach considered?

**Comment by hildjj** [comment]
I've since switched t a WeakMap approach.  I'll look at adding support for tags 28 and 29 as an non-default option, since that will take two passes.

**Comment by hildjj** [comment]
Fixed in 9.0.0
