### ISSUE TITLE
Add BigInt support

### ISSUE THREAD

**Issue by hildjj** [hildjj/node-cbor#80]
Node 10.7 implements BigInt

**Comment by hildjj** [comment]
I'd like someone else to review this if possible, please.

**Comment by cbettinger** [comment]
Is there any way to tell cbor to use BigNumber again on platforms that do not support BigInt?

**Comment by hildjj** [comment]
No.  There are a few options you could take:

- Upgrade your environment to support a modern enough JS.  If your platform is the web, then obviously that won't work for you.  If it's ReactNative, see #156 and https://github.com/facebook/react-native/issues/28492.
- Don't send BigInts in your protocol (If this is your approach, I'm willing to take patches that test for BigInt support before trying to do any BigInt work, particularly if there is a way to test for that)
- Use Babel+babel-plugin-transform-bigint (or a similar combo) to polyfill.

**Comment by hildjj** [comment]
@cbettinger see how one person solved it here: https://github.com/Path-Check/universal-verifier-app/blob/dd41eaf8c2b3f927541112ec71a65ca14cc2424d/index.js

**Comment by cbettinger** [comment]
Thank you very much for your research!

**Comment by hildjj** [comment]
@cbettinger I've added a `cbor-rn-prereqs` package that should a) make this easier for others, and b) ensure the code we came up with is tested.  I updated https://github.com/hildjj/node-cbor-expo-example to use it.  See https://github.com/hildjj/node-cbor/tree/main/packages/cbor-rn-prereqs for details.
