### ISSUE TITLE
Add option to filter undefined values

### ISSUE THREAD

**Issue by misos1** [hildjj/node-cbor#83]
I think there is difference between undefined in javascript and undefined type in cbor (https://tools.ietf.org/html/rfc7049#section-3.8). In cbor it means rather item with encoding problem, but in javascript undefined is more often associated with key or argument which does not exists for example when is function called with less arguments than it has then all "optional" arguments will become undefined.

Seems some cbor deserialisers treats undefined in place of optional value as error instead of ignoring it but accepts null or when is key not encoded in cbor.

Would be nice to have option to not include keys with undefined values.

**Comment by hildjj** [comment]
I'm willing to add an option, but how would the decoder know that this value is optional?

**Comment by misos1** [comment]
Lets say decoder in different language than javascript accept for some key non-present value, null or number. But it treats undefined as some problem because cbor undefined is probably not same thing as javascript undefined. Maybe it was inspired by javascript but json does not have undefined and not many languages have undefined. So such option would be great.

**Comment by hildjj** [comment]
Do you want this for both the encoder and decoder?  I assume you want an error to be thrown if `undefined` is detected?

**Comment by misos1** [comment]
I am ok just with encoder. So when is that option enabled this two examples will have same cbor representation:
```
{
  a: 10,
  b: undefined,
  c: {[
    d: undefined,
    e: 20
  ]}
}
```
```
{
  a: 10,
  c: {[
    e: 20
  ]}
}
```
Maybe this should filter also undefined in arrays like [10, undefined, 20] will become [10, 20].

**Comment by hildjj** [comment]
Other test cases:

- plain undefined
- undefined in an object stream (using the mechanism from #82)
- undefined in a byte stream or text stream
- undefined as a map key (dumb, but technically valid)
- a tagged undefined

**Comment by hildjj** [comment]
I implemented this a while ago, and didn't mark this closed.  This will be in the 4.1.6 release.

**Comment by ninevra** [comment]
I see that `encodeUndefined` allows throwing an error when `undefined` is present in the input - but did the feature in https://github.com/hildjj/node-cbor/issues/83#issuecomment-412139114, omitting `undefined`-valued properties from objects, get implemented? It would be nice to have the option to encode `{foo: undefined}` as `{}`, for protocols where the presence of an undefined-valued property is irrelevant (which is probably going to be the case for most protocols going from javascript to javascript).

`cbor.encode({foo: undefined})` takes up 6 bytes to `cbor.encode({})`'s one byte. Having this option would help with determinism too; it's tedious to write & test javascript code that deterministically does or does not produce `undefined`-valued properties.

**Comment by hildjj** [comment]
@ninevra can you create a new issue as a feature request, please? That's not in yet, but it's a fine idea.

**Comment by misos1** [comment]
@hildjj Sorry that I was not clear but this issue actually meant exactly what @ninevra wrote in comment and described in #134  (not to throw error in case of undefined).

**Comment by hildjj** [comment]
Well, now we have both. :)

Try the new `omitUndefinedProperties` option, and let me know if it works the way you want or not.  Please feel free to file another issue if you want something different.
