### ISSUE TITLE
Switch to jsbi

### ISSUE THREAD

**Issue by hildjj** [hildjj/node-cbor#90]
See https://github.com/dignifiedquire/borc/issues/37

**Comment by hildjj** [comment]
Hm.  JSBI only supports bigints, and not float bignums.  I assume people that want JSBI don't care about those?

**Comment by vmx** [comment]
We do care, but I didn't know that we need decimal support (I have use CBOR just a bit so far).

**Comment by hildjj** [comment]
I already added support for serializing JS bignums and parsing to them if you have bignum support.  It was just a few lines of code, and probably does a bunch of what you want.

**Comment by hildjj** [comment]
OK, now that I've made BigInts on by default in v6.0.0, I'm going to close this as "overcome by events".
