### ISSUE TITLE
Problem encoding `Uint8Array`

### ISSUE THREAD

**Issue by vantuz-subhuman** [hildjj/node-cbor#92]
## Problem
Code example:
```
const cbor = require('cbor');

const arr1 = [1, 2, 3, 4];
console.log(cbor.encode(arr1));
console.log(cbor.decode(cbor.encode(arr1)));

const arr2 = new Uint8Array([1, 2, 3, 4]);
console.log(cbor.encode(arr2));
console.log(cbor.decode(cbor.encode(arr2)));
```

Result:
```
<Buffer 84 01 02 03 04>
[ 1, 2, 3, 4 ]
<Buffer a4 61 30 01 61 31 02 61 32 03 61 33 04>
{ '0': 1, '1': 2, '2': 3, '3': 4 }
```

## Expected
```
<Buffer 84 01 02 03 04>
[ 1, 2, 3, 4 ]
<Buffer 68 01 02 03 04>
Uint8Array [ 1, 2, 3, 4 ]
```
OR
```
<Buffer 84 01 02 03 04>
[ 1, 2, 3, 4 ]
<Buffer 44 01 02 03 04>
<Buffer 01 02 03 04>
```

## Comments
["BORC"](https://github.com/dignifiedquire/borc) produces second result in node setting and first result in browser setting (after "browserify").

E.g. this is how both libraries look in browser:
![image](https://user-images.githubusercontent.com/5585355/50084532-5f195380-0208-11e9-9bfd-8bba89bd70b2.png)

**Comment by hildjj** [comment]
Released 4.1.4 with support for all of the TypedArrays.
