### ISSUE TITLE
Incorrect use of readable.read() in _encodeAll() [BUG]

### ISSUE THREAD

**Issue by misos1** [hildjj/node-cbor#93]
``` node js
let cbor = require("cbor");

let str = "";
for(let i = 0; i < 16375; i++)
	str += "a";

cbor.decodeFirstSync(cbor.encode({ str, v: 10 }));
```

```
Error: Insufficient data
    at Object.decodeFirstSync (.../node_modules/cbor/lib/decoder.js:158:15)
```

When is 16375 changed to 16374 then there is no exception. Node version 12.5.0.

Seems that in encoded cbor is missing value "v".

Bug is here:
``` node js
  _encodeAll(objs) {
    const bs = new NoFilter()
    this.pipe(bs)
    for (const o of objs) {
      if (typeof o === 'undefined') {
        this._pushUndefined()
      } else if (o === null) {
        this._pushNull(null)
      } else {
        this.write(o)
      }
    }
    this.end()
    return bs.read()
  }
```

Function bs.read() may not always read all data produced by Encoder but just content of node js stream internal buffer (which has default size 16384 bytes). This function must be called multiple times.

Here is example of correct way how to use it:

https://nodejs.org/api/stream.html#stream_readable_read_size

"Note that the while loop is necessary when processing data with readable.read()"

Or better would be to concat buffers from "data" event and return as result and you will not need that "NoFilter".

Similar bug is probably also on other places like decodeFirstSync and other "sync" functions.

**Comment by hildjj** [comment]
This is a great bug report -- very actionable.  Thank you, I'll get into it soon.   I'd also take a PR if you have one handy that passes all of the existing tests and adds a new one that shows this problem.

**Comment by hildjj** [comment]
I'm not ready to give up encode() and encodeOne() being synchronous yet -- that would be a big API change.  As a quick fix, I'm going to ensure that highWaterMark works correctly for encode and encodeOne, and write some better docs in the readme about highWaterMark.  I'll also add readme text  preferring to use streaming mode for applications that have any non-trivial needs, with an example creating a new encoder then calling pushAny() on it.

**Comment by hildjj** [comment]
So for the above example:

```
cbor.decodeFirstSync(cbor.encodeOne({ str, v: 10 }, {highWaterMark: 65536}))
```

works after then incoming patch.

**Comment by misos1** [comment]
It may be not always predictable how big would be data after encoding.

This would require some more fundamental rework, probably synchronous encoding not based on streams in background as you cannot get arbitrary large data from stream synchronously very well. Or use stream with dynamically expanding buffer and return it directly if this is doable at all.

What I am missing in API is asynchronous function which returns promise/callback like `decodeFirst`. There is no equivalent for encoding. There is only stream based encoding. It is probably better to use asynchronous methods anyway. Except on places where one would also use other sync functions like `fs.readFileSync`.

**Comment by hildjj** [comment]
I am adding an `encodeAsync()` function, and adding it to the readme in the section mentioned above.  It's docs call out its undesirable use of memory.
